Feature/gh 124 preview bugs
MauroDataMapper-NHSD/mdm-plugin-nhs-data-dictionary pull request #130
Opened 2024-09-20 10:05 UTC by pjmonks

Fixes #127 
Fixes #126 

Minor data dictionary page preview fixes.

- Hides the "Format/Length" section on a Data Element page when the Data Element is retired
- If a National/Default Code (Term) is marked as retired, the retired date is rendered as-is correctly. This is because it is stored as a string, so there are no guarantees it is a structured date value.

2024-09-20 17:33 UTC, OButlerOcc requested changes
![image](https://github.com/user-attachments/assets/a12ad5fa-f673-4be1-99f1-e7ac31fed147)


![image](https://github.com/user-attachments/assets/3a7dbd8a-2cbf-4dfe-bdf3-526fe6a4011d)


First part doesnt seem to be working.. or I retired incorrectly. Will ask monday

I might just not understand retired stuff, I can retire it, bit I can't see a retirement date on a term even thought its marked retired

And the retired element length still appears as normal

2024-09-20 17:33 UTC, OButlerOcc commented on src/main/groovy/uk/nhs/digital/maurodatamapper/datadictionary/NhsDDCode.groovy
> +                // The profile field to store the retired date is just a "string" type, so just have to assume
could force it through a regex validator? If we know our valid date formats that's quite easy

2024-09-20 17:41 UTC, OButlerOcc requested changes
![image](https://github.com/user-attachments/assets/a12ad5fa-f673-4be1-99f1-e7ac31fed147)


![image](https://github.com/user-attachments/assets/3a7dbd8a-2cbf-4dfe-bdf3-526fe6a4011d)


First part doesnt seem to be working.. or I retired incorrectly. Will ask monday

2024-09-23 13:10 UTC, OButlerOcc approved these changes
![image](https://github.com/user-attachments/assets/676573c7-94d0-4022-b4f3-c12abbb422ff)

Term working

![image](https://github.com/user-attachments/assets/fdd91996-6369-438e-93c5-490b49394f34)

This is working but how was it even an issue? I had to mark its place in the preview, retire it, then use the url to get back to it. Retiring the element removes it from the element list.

I'm Prob misunderstanding a use case but it now does what its supposed to.

2024-09-23 13:34 UTC, merged

2024-09-23 13:35 UTC, pjmonks commented
When an issue is retired it does not appear in the usual table of contents links. It does appear under an "All Items Index" though.