Documentation for the NHS DD plugin and publication process
MauroDataMapper-NHSD/mdm-plugin-nhs-data-dictionary pull request #94
Opened 2024-08-09 10:54 UTC by pjmonks

Resolves #86 
Resolves #87 

Documentation updates to provide to NHS Data Solutions explaining the plugin, previewing and publication process.

2024-08-12 18:03 UTC, OButlerOcc requested changes
Clear and reads well, makes sense. On the images thing. Intellij markup can't preview images for some reason but I've confirmed the names match the content. Can you just check they show up properly before we merge this? Also one typo and the jenkins links need updating

2024-08-12 18:03 UTC, OButlerOcc commented on README.md
> +| main    | [![Build Status](https://jenkins.cs.ox.ac.uk/buildStatus/icon?job=Mauro+Data+Mapper-NHSD%2Fmdm-mdm-plugin-nhs-data-dictionary%2Fmain)](https://jenkins.cs.ox.ac.uk/blue/organizations/jenki
Either I can't get to where these links go or they died in the great jenkins housefire of 2024

2024-08-12 18:03 UTC, OButlerOcc commented on README.md
> +Clone the `mdm-application-build` repo, then modify the `build.gradle` file to include the `mdm-plugin-nhs-data-dictionary` plugin:
might need revising following the ongoing mdm build issues but hopefully not

2024-08-12 18:03 UTC, OButlerOcc commented on README.md
> +| main    | [![Build Status](https://jenkins.cs.ox.ac.uk/buildStatus/icon?job=Mauro+Data+Mapper-NHSD%2Fmdm-mdm-plugin-nhs-data-dictionary%2Fmain)](https://jenkins.cs.ox.ac.uk/blue/organizations/jenki
These links no longer work. I assume its the same for all the jenkins links

2024-08-12 18:03 UTC, OButlerOcc commented on docs/endpoints.md
> +All endpoints listed here presume that there is a base domain preceding them e.g. if running under the NHS England test environment https://mauro.dev.dataproducts.nhs.uk/, then the branches endpoint
I still can't get to: https://mauro.dev.dataproducts.nhs.uk/ but I assume the link works

2024-08-12 18:03 UTC, OButlerOcc commented on docs/endpoints.md
> +
its possible to see these in progress jobs in mdm ui, is it worth explaining that here? or maybe just a reference to the jobs part of the mdm ui docs?

2024-08-12 18:03 UTC, OButlerOcc commented on docs/endpoints.md
> +```
I highlighted this is a previous pr, but not including a release date caused issues before. Just as long as we know. See PR https://github.com/MauroDataMapper-NHSD/mdm-plugin-nhs-data-dictionary/pull/78

2024-08-12 18:03 UTC, OButlerOcc commented on docs/endpoints.md
> +Returns the set of statistics calculated for a Data Dictonary branch, such as how many items are retired or preparatory.
typo in dictionary

2024-08-12 18:03 UTC, OButlerOcc commented on docs/previews.md
> +- https://mauro.dev.dataproducts.nhs.uk/orchestration/ - TEST
I can't see these? do they work?

2024-08-12 18:03 UTC, OButlerOcc commented on docs/previews.md
> +![](/docs/images/website-preview.png)
these images don't display in the markdown preview but appear to be correct. just confirm for me before you merge you can see them?

2024-08-12 18:03 UTC, OButlerOcc commented on docs/previews.md
> +Once completed, the content that would appear in the final PDF change paper will appear. Note that the appearance will not exactly match - this is a _content_ preview only.
fair statement

2024-08-13 08:36 UTC, pjmonks commented on README.md
> +| main    | [![Build Status](https://jenkins.cs.ox.ac.uk/buildStatus/icon?job=Mauro+Data+Mapper-NHSD%2Fmdm-mdm-plugin-nhs-data-dictionary%2Fmain)](https://jenkins.cs.ox.ac.uk/blue/organizations/jenki
We can't do anything about this yet because we need a GitHub Actions pipeline. I've added #98 to fix this later.

2024-08-13 08:38 UTC, pjmonks commented on README.md
> +Clone the `mdm-application-build` repo, then modify the `build.gradle` file to include the `mdm-plugin-nhs-data-dictionary` plugin:
Again, this will have to be adjusted later because any updated process for building locally has not been defined yet.

2024-08-13 08:38 UTC, pjmonks commented on README.md
> +| main    | [![Build Status](https://jenkins.cs.ox.ac.uk/buildStatus/icon?job=Mauro+Data+Mapper-NHSD%2Fmdm-mdm-plugin-nhs-data-dictionary%2Fmain)](https://jenkins.cs.ox.ac.uk/blue/organizations/jenki
See #98

2024-08-13 08:39 UTC, pjmonks commented on docs/endpoints.md
> +All endpoints listed here presume that there is a base domain preceding them e.g. if running under the NHS England test environment https://mauro.dev.dataproducts.nhs.uk/, then the branches endpoint
All the NHS England hosted websites have correct, accessible URLs - I'm able to access all of them, as are NHS England.

2024-08-13 08:56 UTC, pjmonks commented on docs/previews.md
> +- https://mauro.dev.dataproducts.nhs.uk/orchestration/ - TEST
Yes they do

2024-08-13 08:57 UTC, pjmonks commented on docs/previews.md
> +![](/docs/images/website-preview.png)
They are visible in GitHub when viewing the markdown files in preview, plus in VS Code.

2024-08-13 08:59 UTC, pjmonks commented on docs/endpoints.md
> +
Good point, I've added a paragraph to explain about async jobs.

2024-08-13 09:00 UTC, pjmonks commented on docs/endpoints.md
> +```
I've added more details on the folder version number parameters to hopefully make it clearer what to set.

2024-08-13 09:00 UTC, pjmonks commented on docs/endpoints.md
> +Returns the set of statistics calculated for a Data Dictonary branch, such as how many items are retired or preparatory.
Thanks, fixed.

2024-08-13 09:01 UTC, pjmonks commented
I've made some updates from your feedback, thanks. The images do render because I can see them in GitHub, where I would expect they are most likely to be read.

2024-08-13 10:04 UTC, OButlerOcc approved these changes
Changes look good, saw your comments on the links. Happy to approve

2024-08-13 10:10 UTC, merged